spring.application.name=ecommerce

# Configurações de Conexão com o SQL Server (Banco MOINHO)
spring.datasource.url=jdbc:sqlserver://192.168.0.201;databaseName=MOINHO;encrypt=true;trustServerCertificate=true;
spring.datasource.username=super
spring.datasource.password=sqlserver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Nome e local do arquivo de log principal
logging.file.name=logs/sincronizador-precos.log

# Cria um arquivo novo por dia (o %i numera o arquivo se ele ficar muito grande)
logging.logback.rollingpolicy.file-name-pattern=logs/sincronizador-precos-%d{yyyy-MM-dd}.%i.log

# Mantém apenas os logs dos últimos 30 dias (evita lotar o HD)
logging.logback.rollingpolicy.max-history=30
